name: Hello World!
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "Running test case"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploying the App"

