name: Hello World!
on:
  push:
    branches:
      - main
      - develop
      - 'realeses/**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Demo build"
 
