name: If demo
on:
  push:
    branches:
      - main
      - develop

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main'
        run: echo "Running for main branch"
      - name: Run this step
        run: echo "Running this step"        
